version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj
    ports:
      - '3313:3313'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
   driver: local